import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import Header from '@/modules/header/Header'
import Homepage from '@/modules/homepage/Homepage'
import Projects from '@/modules/projects/Projects'
import ProcessApps from '@/modules/processApps/ProcessApps'
import Pricing from '@/modules/pricing/Pricing'
import AboutUs from '@/modules/aboutus/AboutUs'
import Footer from '@/modules/footer/Footer'

const inter = Inter({subsets: ['latin']})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Homepage />
      <Projects />
      <ProcessApps />
      <Pricing />
      <AboutUs />
      <Footer />
    </>
  )
}
